// This file has been autogenerated from a class added in the UI designer.

using System;
using ConfigDemo.iOS.Datasources;
using ConfigDemo.Models;
using Foundation;
using UIKit;

namespace ConfigDemo.iOS
{
	public partial class FeatureFlagsViewController : UITableViewController
	{
		public FeatureFlags _Flags;
		bool _IsFlags => this._Flags != null;

		public FeatureFlagsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.TableView.RegisterNibForCellReuse(PropertyTableViewCell.Nib, PropertyTableViewCell.Key);
            this.TableView.RowHeight = UITableView.AutomaticDimension;
            this.TableView.EstimatedRowHeight = 44;
            this.TableView.TableFooterView = new UIView();
            this.TableView.BackgroundColor = UIColor.FromName("color-dark-1");

            if (this._IsFlags)
            {
                GetFeatureFlags();
            }
        }

        void GetFeatureFlags()
        {
            var source = new FeatureFlagsDatasource(this._Flags);
            this.TableView.Source = source;
            this.TableView.ReloadData();
        }

    }
}
