// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using ConfigDemo.iOS.Datasources;
using Foundation;
using UIKit;

namespace ConfigDemo.iOS
{
	public partial class MessagesViewController : UITableViewController
	{
		public List<object> _Messages;
		bool _IsMessages => this._Messages != null;

		public MessagesViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.TableView.RegisterNibForCellReuse(PropertyTableViewCell.Nib, PropertyTableViewCell.Key);
            this.TableView.RowHeight = UITableView.AutomaticDimension;
            this.TableView.EstimatedRowHeight = 44;
            this.TableView.TableFooterView = new UIView();

            if (this._IsMessages)
            {
                GetMessages();
            }


        }

        void GetMessages()
        {
            var source = new MessagesDatasource(this._Messages);
            this.TableView.Source = source;
            this.TableView.ReloadData();
        }
    }
}
