// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ConfigDemo.iOS
{
	public partial class MessagesViewController : UITableViewController
	{
		public MessagesViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
