// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using ConfigDemo.iOS.Datasources;
using ConfigDemo.Models;
using Foundation;
using UIKit;

namespace ConfigDemo.iOS
{
    public partial class OrganizationsViewController : UITableViewController
    {
        //make them not public
        public List<Organization> _Org;

        bool _IsOrg => this._Org != null;

        public OrganizationsViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            this.TableView.RegisterNibForCellReuse(PropertyTableViewCell.Nib, PropertyTableViewCell.Key);
            this.TableView.RowHeight = UITableView.AutomaticDimension;
            this.TableView.EstimatedRowHeight = 44;
            this.TableView.TableFooterView = new UIView();
            this.TableView.BackgroundColor = UIColor.FromName("color-dark-1");

            if (this._IsOrg)
            {
                GetOrgItems();
            }


        }

        void GetOrgItems()
        {
            var source = new OrganizationsDatasource(this._Org, this);
            this.TableView.Source = source;
            this.TableView.ReloadData();
        }
    }
}
