// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ConfigDemo.iOS
{
	public partial class SecondLevelViewController : UIViewController
	{
		public SecondLevelViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

			this.TableView.RegisterNibForCellReuse(ObjectTableViewCell.Nib, ObjectTableViewCell.Key);
			this.TableView.RegisterNibForCellReuse(PropertyTableViewCell.Nib, PropertyTableViewCell.Key);
			this.TableView.RowHeight = UITableView.AutomaticDimension;
			this.TableView.EstimatedRowHeight = 44;
			this.TableView.TableFooterView = new UIView();
		}
    }
}
